pointcloud_fusion:
  ros__parameters:
    output_topic: "/merged_points"
    fixed_frame: "base_link"

    self_box:
      enabled: true
      cx: 0.0
      cy: 0.0
      length: 0.70   # X (앞-뒤)
      width:  0.55   # Y (좌-우)
      yaw_deg: 0.0   # base_link와 평행이면 0
      margin: 0.03   # 2~5cm 권장, 일단 3cm
      use_z: false
      z_min: -0.10
      z_max:  0.60

    extra_box:
      enabled: false
      cx: 0.0
      cy: 0.0
      length: 0.30
      width:  0.25
      yaw_deg: 0.0
      margin: 0.0
      use_z: false
      z_min: -0.10
      z_max:  0.60

    radius_filter:
      enabled: false
      r: 0.55
      cx: 0.0
      cy: 0.0
